name: New theme bundle

on:
  repository_dispatch:
    types: [new_theme_bundle]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: echo event
        run: |
          echo "${{ github.event.client_payload.ref }}"
