name: New theme bundle

on:
  repository_dispatch:
    types: [new_theme_bundle]
  workflow_dispatch:
    inputs:
      release:
        description: 'release'
        type: string
        required: false
      bundle_file:
        description: 'bundle_file'
        type: string
        required: false
      bundle_url:
        description: 'bundle_url'
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:  
      - name: Checkout
        uses: actions/checkout@v2       
      - name: Setup Perl environment
        uses: shogo82148/actions-setup-perl@v1.15.3
      - name: echo event
        run: |
          echo "${{ github.event.client_payload.release }}"
          echo "${{ github.event.client_payload.file }}"
          echo "${{ github.event.client_payload.url }}"
        env:
          release_name: echo "${{ github.event.client_payload.release }}"
          bundle_file: echo "${{ github.event.client_payload.file }}"
          bundle_url: echo "${{ github.event.client_payload.url }}"
          
      - name: Update theme bundle in Antora playbook
        run: |
          perl -007 -i -pe 's?.*ui:.*\n.*bundle:.*\n.*url:.*?ui:\n  bundle:\n    url: '$bundle_url'?' antora-playbook.yml
          cat antora-playbook.yml    
          
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Update Antora playbook with bundle $bundle_file
